[project]
name = "chanscrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "urllib3>=2.5.0",
]
